### ISSUE TITLE
Installing php54 with phpdbg

### ISSUE THREAD

**Issue by dsdeiz** [Homebrew/homebrew-php#1397]
Trying to install php54 with phpdbg and I get this error:

```bash
$ brew install php54 --with-phpdbg
==> Downloading http://www.php.net/get/php-5.4.33.tar.bz2/from/this/mirror
Already downloaded: /Library/Caches/Homebrew/php54-5.4.33
Warning: Backing up all known pear.conf and .pearrc files
Warning: If you have a pre-existing pear install outside
         of homebrew-php, or you are using a non-standard
         pear.conf location, installation may fail.
==> Downloading https://github.com/krakjoe/phpdbg/archive/v0.3.2.tar.gz
Already downloaded: /Library/Caches/Homebrew/php54--phpdbg-0.3.2.tar.gz
==> ./buildconf --force
==> ./configure
Error: inreplace failed
Makefile:
  expected replacement of /^INSTALL_IT = \$\(mkinstalldirs\) '([^']+)' (.+) LIBEXECDIR=([^\s]+) (.+)$/ with "INSTALL_IT = $(mkinstalldirs) '/usr/local/Cellar/php54/5.4.33/libexec/apache2' \\2 LIBEXECDIR='/usr/local/Cellar/php54/5.4.33/libexec/apache2' \\4"
```

Any ideas what I might be missing?

**Comment by alanthing** [comment]
Some changes have been made to the formulas that may address this issue. Closing, but feel free to re-open if this persists.

**Comment by dsdeiz** [comment]
Unfortunately this still happens to me. I did `brew update` and the following:

1. `brew remove php54`
2. `brew unlink php54`
3. `brew install php54 --with-php-dbg`

I get this:

```
==> Downloading https://github.com/krakjoe/phpdbg/archive/v0.3.2.tar.gz
Already downloaded: /Library/Caches/Homebrew/php54--phpdbg-0.3.2.tar.gz
==> ./buildconf --force
==> ./configure
Error: inreplace failed
Makefile:
  expected replacement of /^INSTALL_IT = \$\(mkinstalldirs\) '([^']+)' (.+) LIBEXECDIR=([^\s]+) (.+)$/ with "INSTALL_IT = $(mkinstalldirs) '/usr/local/Cellar/php54/5.4.37/libexec/apache2' \\2 LIBEXECDIR='/usr/local/Cellar/php54/5.4.37/libexec/apache2' \\4"
```

Thanks!

**Comment by xurumelous** [comment]
Hello @dsdeiz,

I could get around this problem, but I'm still not sure if it can give me some trouble. Everything appears ok.

First I installed each version without options (e.g.: `brew install php56`), then I applied the patch below and executed `brew reinstall php56 --with-phpdbg` and the other options I needed.

I did not tried with php 5.3, but for 5.4, 5.5 and 5.6, this patch solved the problem: https://gist.github.com/xurumelous/da081a7e09ee9e4c486e

I checked the generated Makefile while brew was installing, and the variable `INSTALL_IT` was empty, that's why the `inreplace` throws an error.

For php 5.6, I also used this to update the phpdbg to 0.4.0: https://gist.github.com/xurumelous/1429b6cc2004e5448823

Manually compiling php, I could use only 0.3.2 for php 5.4 and 5.5 and 0.4.0 for php 5.6.

I did not make a pull-request with those patches, because there was a problem when installing for the first time.

Hope it helps you.

//xurumelous

**Comment by xurumelous** [comment]
Hello @alanthing, should not this issue be reopened? :)

**Comment by macdaddy** [comment]
Ran into the same issue attempting to install php56 --with-phpdbg on Yosemite. Definitely needs to be fixed still!

**Comment by bredman** [comment]
Also ran into the same issue while trying `brew install php56 --with-phpdbg` on Yosemite. Tried the patch above which allowed things to complete but I didn't end up with `phpdbg` installed

**Comment by bredman** [comment]
For what it's worth I got around this by using the Formula from version 743f4d8b3322ecd7cb2db711bb5091fb48b59115 of the homebrew-php repo.

```
cd /usr/local/Library/Taps/homebrew/homebrew-php
git checkout 743f4d8b3322ecd7cb2db711bb5091fb48b59115
brew install php56 --with-phpdbg
```

**Comment by alanthing** [comment]
Found the problem, test pending.

**Comment by dsdeiz** [comment]
Just to inform, I am not able to reproduce the problem anymore with the latest updates. Thanks @alanthing!

**Comment by tboyce12** [comment]
```
$ brew update
Already up-to-date.
$ brew install -v php56 --with-phpdbg
==> Installing php56 from homebrew/homebrew-php
Error: phpdbg is not supported for this version of PHP
```

:(

**Comment by james2doyle** [comment]
Just ran `brew reinstall -v php70 --with-phpdbg` and everything worked.

Checked the install with `php -i | grep dbg` and the flag was there.
