### ISSUE TITLE
Error 139 - make: *** [ext/phar/phar.php]

### ISSUE THREAD

**Issue by lutfiqaraman** [Homebrew/homebrew-php#1426]
I'm using homebrew to install php 5.6 It gives me a message "make: *** [ext/phar/phar.php] Error 139". 

How can I solve that error? Anyone can give some help? Many thanks!

Here what I did to install php 5.6 

$ brew doctor
Your system is ready to brew.

$brew update
Already up-to-date.

$ brew --config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew.git
HEAD: 2f84b834f37ccead3baaf8e707afbe5dcd498b77
Last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: 8-core 64-bit sandybridge
OS X: 10.10-x86_64
Xcode: 6.1
CLT: 6.1.0.0.1.1413057044
Clang: 6.0 build 600
X11: N/A
System Ruby: 2.0.0-481
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby

$ brew install php56
make: *** [ext/phar/phar.php] Error 139

Anyone can give some help? Many thanks!

**Comment by predominant** [comment]
Also having the same issue

$ brew --config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: b11179c1c8dfd0604c040643569e59d85e38aba1
Last commit: 7 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: quad-core 64-bit haswell
OS X: 10.10.1-x86_64
Xcode: 6.1.1
CLT: 6.1.1.0.1.1416017670
Clang: 6.0 build 600
X11: N/A
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby

**Comment by danielson317** [comment]
Same issue. Probably caused by Yosimite (OS X: 10.10.*)
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew.git
HEAD: 65f7c8fa64067a56c6241e3d125b1b0a105a0f4e
Last commit: 20 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: dual-core 64-bit penryn
OS X: 10.10.1-x86_64
Xcode: 6.1.1
CLT: 6.1.1.0.1.1416017670
Clang: 6.0 build 600
X11: N/A
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby

**Comment by danielson317** [comment]
use `brew reinstall php54 --with-mssql --without-snmp` according to https://github.com/Homebrew/homebrew-php/issues/1326

This case seems to be a duplicate.

**Comment by alanthing** [comment]
Pushed the option to disable snmp by default in 7c56043. Please continue the discussion in #1326.
