### ISSUE TITLE
Composer: Automatically install a php

### ISSUE THREAD

**Issue by mcandre** [Homebrew/homebrew-php#1466]
When the composer formula detects that none of the homebrew-php PHP's are installed, could it automatically install the latest one on behalf of the user?

For newbies, this would simplify the composer installation process a bit.

**Comment by alanthing** [comment]
Since there are 4 different versions of PHP provided here, we can't make one particular version a hard requirement. The [repository README](/Homebrew/homebrew-php) contains instructions for installing `php56` immediately after the tap instructions, so it's assumed that you should at least get that far.
