### ISSUE TITLE
PHPLint install errors

### ISSUE THREAD

**Issue by welly** [Homebrew/homebrew-php#1529]
Hey all,

Having some issues installing PHPLint. The install log is as follows:

```
➜  ~  brew install homebrew/php/phplint
==> Installing phplint from homebrew/homebrew-php
==> Downloading http://www.icosaedro.it/phplint/phplint-pure-c-1.1_20130803.tar.gz
######################################################################## 100.0%
==> Patching
patching file include/missing.c
patching file phpl
==> gcc-4.9 -fnested-functions src/phplint.c -o src/phplint
2015-02-05 08:44:17 +0930

gcc-4.9 -fnested-functions src/phplint.c -o src/phplint

gcc-4.9: error: unrecognized command line option '-fnested-functions'

READ THIS: http://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-php/issues
```

**Comment by jt3k** [comment]
+1
I also install gcc from homebrew

**Comment by haxxxton** [comment]
+1
also on gcc 4.9, having installed via homebrew,

```
gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.1.0
Thread model: posix
```

Versions:
OSX 10.10.2
brew 0.9.5

**Comment by alanthing** [comment]
Looks like the `'-fnested-functions'` addition was needed with OS X had a version of `gcc` with nested functions disabled by default (see [Note 1](http://www.icosaedro.it/phplint/download.html)). Since Apple has moved onto `clang` as the default compiler and this formula still needs `gcc`, the Homebrew `gcc-4.9` *has* nested functions on by default, and this flag is therefore no longer needed.

Please let me know if this does or doesn't solve your build issues. Seems to work better on my end.

**Comment by haxxxton** [comment]
ended up getting this working by `brew uninstall gcc` and then `brew install homebrew/dupes/apple-gcc42`.. this then allowed me to install phplint normally
