### ISSUE TITLE
Xdebug 2.3 extension fails to load on php56

### ISSUE THREAD

**Issue by johnbillion** [Homebrew/homebrew-php#1646]
I recently updated `php56-xdebug` from version 2.2.7 to 2.3.2, and the extension now fails to load. If I switch back to the older version it works as expected.

I can see that PHP is loading `ext-xdebug.ini` as it's listed under 'Additional .ini files parsed' in phpinfo, and `ext-xdebug.ini` correctly references the extension file:

```ini
[xdebug]
zend_extension="/usr/local/opt/php56-xdebug/xdebug.so"
```

Despite this, the extension simply doesn't load. Disabling my other PHP extensions doesn't help.

What can I do to debug this?

PHP is version 5.6.7 (using `php56`). OS X is 10.10.1. Homebrew is 0.9.5.

**Comment by johnbillion** [comment]
It just ocurred to me that this might be related to #1615 or #1556, and indeed it looks like it is. I just installed Xdebug with `brew install php56-xdebug --build-from-source` and the extension loads as expected.

**Comment by hacfi** [comment]
Same issue here on 10.9.3..following @johnbillion’s instructions now

**Comment by hacfi** [comment]
I accidentally used port 9000 which was used by php-fpm itself. Not sure if the bottled version works as I built it from source.

**Comment by alanthing** [comment]
Closing as I have removed the bottles. Due to the variances of xdebug and PHP and whether or not certain debug options should be used when building binaries, it seems ideal to alway shave xdebug build from source.

For others finding their way here from searches, run a `brew update` before attempting to [re]install xdebug to ensure it builds from source.
