### ISSUE TITLE
brew php70-redis in only-head formula

### ISSUE THREAD

**Issue by bfontaine** [Homebrew/homebrew-php#2705]
_From @naffan2014 on December 28, 2015 11:22_

why i type "brew install php70-redis"
and he told me 
"Error: homebrew/php/php70-redis is a head-only formula
Install with `brew install --HEAD homebrew/php/php70-redis`"

what is this mean?

and when i type brew install --HEAD homebrew/php/php70-redis ,he gave me a fatal error

==> Installing php70-redis from homebrew/php
==> Cloning https://github.com/phpredis/phpredis.git
Updating /Library/Caches/Homebrew/php70-redis--git
==> Checking out branch php7
==> /usr/local/opt/php70/bin/phpize
==> ./configure --prefix=/usr/local/Cellar/php70-redis/HEAD --with-php-config=/usr/local/opt/php70/bin/php-
Last 15 lines from /Users/naffan2012/Library/Logs/Homebrew/php70-redis/02.configure:

./configure
--prefix=/usr/local/Cellar/php70-redis/HEAD
--with-php-config=/usr/local/opt/php70/bin/php-config

checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... /usr/local/Library/ENV/4.3/sed
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... configure: error: in `/private/tmp/php70-redis20151228-6273-1882z36':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/php/issues

what can i do?

_Copied from original issue: Homebrew/homebrew#47448_

**Comment by bfontaine** [comment]
Please read the link in the error message and follow what it says:
> READ THIS: https://git.io/brew-troubleshooting

 

> what is this mean?

This means the formula doesn’t provide any stable release. Using `--HEAD` you can install from the `HEAD` of the formula, which is usually unstable.

**Comment by naffan2014** [comment]
before i ask this quesion .i have done waht troubleshoooting told me , but it could not help me .so i ask this question through https://github.com/homebrew/php/issues

**Comment by naffan2014** [comment]
and could you tell me where is the config.log ?

**Comment by bfontaine** [comment]
Please post the output of `brew gist-logs homebrew/php/php70-redis`.

**Comment by naffan2014** [comment]
php git:(master) brew gist-logs homebrew/php/php70-redis
https://gist.github.com/84a36d8d166651de15f7

**Comment by naffan2014** [comment]
i have 2 mac  one is air 13  the other is pro 13  .
pro 13 install php70-redis  is  ok.
but air install php70-redis fail .

system are all el capitan

**Comment by naffan2014** [comment]
i type what you said  twice
 first output is https://gist.github.com/84a36d8d166651de15f7
the second output is https://gist.github.com/df7707562d6ada2f324e

why the output are different....:(

**Comment by bfontaine** [comment]
The outputs are different because the command generates a new Gist each time. This is normal; what’s important is not the URL but the logs.

**Comment by bfontaine** [comment]
> Warning: Your Xcode (6.3) is outdated
> Please update to Xcode 7.2.
> Xcode can be updated from the App Store.

You should update Xcode and try again.

**Comment by naffan2014** [comment]
ops . when i brew docter . he told me that xcode is  6.3 is outdated. but i thought it was a warning . so  i ignored it . let me update my xcode then i try again.

by the way .how can you see my xcode is outdated?

**Comment by naffan2014** [comment]
but do you really think xcode is the problem?

**Comment by bfontaine** [comment]
I can see your Xcode is outdated from the `brew doctor` output included in your gist-logs: https://gist.github.com/anonymous/df7707562d6ada2f324e

Some users had a similar build error because of an outdated Xcode, e.g. https://github.com/Homebrew/homebrew/issues/42919.

**Comment by naffan2014** [comment]
ok.i am updating xcode now . 
now i have another problem.could you help me let a look at this quesion. and what is the problem is?



yifandeMacBook-Pro:www naffan$ brew install --HEAD homebrew/php/php70-memcached
==> Installing php70-memcached from homebrew/php
==> Cloning https://github.com/php-memcached-dev/php-memcached.git
Updating /Library/Caches/Homebrew/php70-memcached--git
==> Checking out branch php7
==> /usr/local/opt/php70/bin/phpize
==> ./configure --prefix=/usr/local/Cellar/php70-memcached/HEAD --with-php-config=/usr/
Last 15 lines from /Users/yifanzhang/Library/Logs/Homebrew/php70-memcached/02.configure:
checking for nawk... no
checking for awk... awk
checking if awk is broken... no
checking whether to enable memcached support... yes, shared
checking for libmemcached... yes, shared
checking whether to enable memcached session handler support... yes
checking whether to enable memcached igbinary serializer support... no
checking whether to enable memcached json serializer support... no
checking whether to enable memcached msgpack serializer support... no
checking whether to enable memcached sasl support... yes
checking whether to enable memcached protocol support... no
checking whether to use system FastLZ bibrary... no
checking for ZLIB... yes, shared
checking for pkg-config... /usr/local/opt/pkg-config/bin/pkg-config
checking for zlib location... configure: error: memcached support requires ZLIB. Use --with-zlib-dir=<DIR> to specify the prefix where ZLIB headers and library are located

**Comment by naffan2014** [comment]
may be my homebrew is outdate in me mac pro :) i am upgrading it now

**Comment by bfontaine** [comment]
You don’t have to specify where the ZLIB headers are located; if it doesn’t install as is we’ll need to change the formula. Could you please post the output of `brew gist-logs homebrew/php/php70-memcached`?

**Comment by naffan2014** [comment]
ok  ,  https://gist.github.com/d309aeeb30c939236153

**Comment by naffan2014** [comment]
hi man.are you  online ?

**Comment by bfontaine** [comment]
@naffan2014 Sorry could you open another issue on this repo? It’s easier to follow if each issue refers to one problem.

**Comment by naffan2014** [comment]
https://github.com/Homebrew/homebrew-php/issues/2710
thank you for your advice
