### ISSUE TITLE
arcanist stable branch

### ISSUE THREAD

**Issue by ghost** [Homebrew/homebrew-php#2814]
"brew reinstall --HEAD homebrew/php/arcanist" checks out the default 'master' branch.
Recently the Phabricator folks created a 'stable' branch which is about 1 week behind master and updated regularly ( see https://secure.phabricator.com/book/phabricator/article/upgrading/#stable-branch ).

Is it possible to edit this formula to have the option to checkout the stable branch?

Thanks,
Bye,
Marco

**Comment by javian** [comment]
As I can understand it you can't have both without locking down a specific revision for one of them. --HEAD can point to a specific branch without specifying a revision and could be set to "stable" rather than "master" which is the default. That commit can easily be made into a PR but I'm not sure what the contribution policy says about "near to HEAD" branches but if you feel that adds more value to the software then it might be worthwhile.

Also, homebrew would only deploy a new version of HEAD when you ask for it specifically like

`brew reinstall --HEAD neovim`

would update to the latest neovim release but if I performed  brew update/upgrade then it does not pick up on brewed software using --HEAD .

**Comment by marco-duckma** [comment]
What about forking the formula and create homebrew/php/arcanist-stable ?
Could this be a viable option?
