### ISSUE TITLE
Don't remove xdebug extension from composer

### ISSUE THREAD

**Issue by sharpner** [Homebrew/homebrew-php#3230]
## Description

This commit https://github.com/Homebrew/homebrew-php/commit/03e3b7293034fa74f524d865d649702e886f0d17 is a real nasty hack. 

Our composer.json depends on ext-xdebug for dev environments, and with this new composer version, there is no way to figure out wether the extension got installed, or not.

I know that there is a pesky warning when running composer, but can we make that at least a build flag? Currently the brew version behavious differently than the direct download on getcomposer.org. 

![bildschirmfoto 2016-05-30 um 14 38 37](https://cloud.githubusercontent.com/assets/574362/15649764/39accaa4-2674-11e6-9800-c60e6886f2cf.png)

Related Issues:
https://github.com/Homebrew/homebrew-php/pull/3174
https://github.com/Homebrew/homebrew-php/issues/2937

## Context and Logs

Parameter | Value
--------- | ------------------
**OS X Version:**       | Mac OS X
**Homebrew Version:**   | _Homebrew 0.9.9 (git revision d20c1; last commit 2016-05-30)_
**PHP Version in use:** | php-56

**Comment by javian** [comment]
I agree, I'll revert the commit for the time being pending a more non-intrusive solution.

**Comment by josegonzalez** [comment]
Closing, as I think letting users control their environments by installing/uninstalling extensions is better than us trying to appease people wanting to get rid of a warning from composer.

Personally I think it's an issue in composer if there is such a severe performance penalty for having xdebug enabled, and they should figure out how to fix it there, rather than forcing their choices upon PHP distributors.
