### ISSUE TITLE
brew removed /usr/local/Library/ENV so phpize is broken.

### ISSUE THREAD

**Issue by dalejung** [Homebrew/homebrew-php#3352]
## Description

Just a heads up. https://github.com/Homebrew/brew/pull/507 broke `phpize` currently found in the bottles. `SED="@@HOMEBREW_PREFIX@@/Library/ENV/4.3/sed"` no longer works. I had to build from source to fix this.

**Comment by Ashot-KR** [comment]
Will it ever be fixed?

-
For those who has problem with installing extensions for php(in my case it was some dependancy for `php70-memcached`), little workaround:
edit `/usr/local/Cellar/php70/7.0.8/bin/phpize` (path can be different, dependant on php version)
change `SED` variable value to `/usr/bin/sed` (`sed` location can be checked with `which sed`)

**Comment by chimneysweep13** [comment]
@Ashot-KR Until it will be fixed it is probably better not to edit files in all versions of php in `bin` dir, but instead make temporary symlink so both of `php-config` and `phpize` can work properly e.g.:
```
mkdir -p /usr/local/Library/ENV/4.3/
ln -s /usr/local/Library/Homebrew/shims/super/sed /usr/local/Library/ENV/4.3/sed
```
This problem occurs because of "move to new paths" https://github.com/Homebrew/brew/pull/507/commits/36efa1a9b9f77b742ae5496e75a6efb08ef3d175

**Comment by Ashot-KR** [comment]
@chimneysweep13 Your solution much better, didn't think about it at that moment. I just needed a quick fix 😄

**Comment by IanGely** [comment]
@chimneysweep13 Your solution solve my question perfactly, thanks :laughing:

**Comment by javian** [comment]
This should now be resolved due to regenerated bottles.

**Comment by emb03** [comment]
@Ashot-KR your solution worked for me.
