### ISSUE TITLE
Remove no longer supported PHP versions

### ISSUE THREAD

**Issue by alcaeus** [Homebrew/homebrew-php#3686]
Note: this was previously discussed in #1327. Back then it was about bringing back PHP 5.2 and/or dropping PHP 5.3.

We have now reached the point where PHP 5.3, 5.4 and 5.5 have been EOLed, leaving 5.6 and 7.0 as the only supported PHP releases (with PHP 7.1 coming soon). Given that 5.3 has been EOLed more than 2 years ago and 5.4 has been EOLed more than 1 year ago, maybe it's time to start removing old formula?

One previous idea was to [drop support for 5.3 when 5.4 is EOLed](https://github.com/Homebrew/homebrew-php/issues/1327#issuecomment-56086692), which essentially means supporting one EOLed version and dropping everything that's older - in this case this would mean dropping 5.3 and 5.4, while leaving 5.5, 5.6 and 7.0 for now. What do you think?

**Comment by javian** [comment]
We were discussing this briefly a little while back and @josegonzalez was thinking along the same lines. I would be fine to do it since it feels odd to support a no longer supported version. We were looking at the statistics for Wordpress - https://wordpress.org/about/stats/ - that shows that there is still a big portion of installations using non supported versions which continues to freak me out =)

One option we discussed was to move over the old formulas to a boneyard repo to keep them alive but not supported.

**Comment by javian** [comment]
I'll see if I can compile some download statistics over the weekend.

**Comment by alcaeus** [comment]
> One option we discussed was to move over the old formulas to a boneyard repo to keep them alive but not supported.

That's a good idea, that way people who have to support older PHP versions can still get packages, while we remove the overhead of updating formulae for dead PHP versions. I won't comment on Wordpress usage statistics - those freak me out too much to think about.

**Comment by pinepain** [comment]
I would even move 5.5 to boneyard. If people want to use outdated version, they have to support them themselves. Vendor lock-in is not an excuse but a faulty policy of such vendors.

**Comment by pinepain** [comment]
Based on stats, php53 and php56 could be removed without any doubts. php55 is also having negative dynamics and could be also considered as a candidate for removal from mainstream. It's nice to see that php71 is raising.

[php53 statistics:](https://bintray.com/homebrew/bottles-php/php53/view#statistics)
![php53](https://cloud.githubusercontent.com/assets/2185793/19200416/8edc3e10-8cd1-11e6-9d73-ccaf57468c48.png)

[php54 statistics:](https://bintray.com/homebrew/bottles-php/php54/view#statistics)
![php54](https://cloud.githubusercontent.com/assets/2185793/19200415/8edaf58c-8cd1-11e6-900c-a7fba0667e1d.png)

[php55 statistics:](https://bintray.com/homebrew/bottles-php/php55/view#statistics)
![php55](https://cloud.githubusercontent.com/assets/2185793/19200418/8edd3216-8cd1-11e6-8043-ee804b0750c7.png)

[php56 statistics:](https://bintray.com/homebrew/bottles-php/php56/view#statistics)
![php56](https://cloud.githubusercontent.com/assets/2185793/19200414/8eda46be-8cd1-11e6-888d-b5c971787596.png)

[php70 statistics:](https://bintray.com/homebrew/bottles-php/php70/view#statistics)
![php70](https://cloud.githubusercontent.com/assets/2185793/19200417/8edc4e46-8cd1-11e6-9a2e-361bef8eeb1f.png)

[php71 statistics:](https://bintray.com/homebrew/bottles-php/php71/view#statistics)
![php71](https://cloud.githubusercontent.com/assets/2185793/19200419/8edf82dc-8cd1-11e6-9450-12f145160f5f.png)

**Comment by josegonzalez** [comment]
5.6 is the currently supported 5.x release, so I'm 👎 on removing that. Also 👎 on removing 5.5 as CakePHP requires at least that (I can play favorites since I started this tap :P).

Anything below 5.5 can be moved to the boneyard imo.

**Comment by pinepain** [comment]
@josegonzalez sorry, not 5.6 but 5.4 was a typo.

5.5 is quite arguable, but afaik CakePHP doesn't require 5.5, it requires [`"php": ">=5.5.9",`](https://github.com/cakephp/cakephp/blob/b03309f98fa281944c91fd0a77ae88d2bd1450d2/composer.json#L21). Can we then remove 5.5 from mandatory version when providing upgrades for formulas?

**Comment by josegonzalez** [comment]
I'd like to support the minimum version, and just having 5.5 around isn't terrible. We can revisit next year.

**Comment by pinepain** [comment]
Makes sense.

**Comment by ablyler** [comment]
I also like the idea of keeping 5.5 as a minimum version.

**Comment by javian** [comment]
Looking at the Google Analytics data we have over the last month

PHP Version | Standard Installs |Custom Installs (using cmd line options)
-------------|------------|----------
5.3 | ~900|~350
5.4 |~2000 |~470
5.5 | ~6300 |~1800
5.6 | ~19400|~6500
7.0 | ~31000|~6100
7.1 | ~5000|~940

**Comment by pinepain** [comment]
Surprisingly, It looks like even 5.4 still quite popular among developers. 

Does Google Analytics count repetitive installation? While GA and bintray statistics correlates, it looks like GA counts all installation types, even reinstall when bottle is already cached.

Does GA have some numbers to figures out actual users number?

**Comment by javian** [comment]
@pinepain yes it does but I was looking at the unique numbers so people who installed it more than once on the same account should not count twice.

Here's an example from php7

![screen shot 2016-10-08 at 15 52 04](https://cloud.githubusercontent.com/assets/527069/19213561/44b6bdb2-8d6f-11e6-90a9-5825c6494f2f.png)

**Comment by alcaeus** [comment]
Looking at the GA numbers @javian posted, we get the following percentages (I added up the regular and custom installs):

PHP version | Percentage
-----------|-----------
5.3 | 1.55%
5.4 | 3.06%
5.5 | 10.03%
5.6 | 32.07%
7.0 | 45.94%
7.1 | 7.36%

PHP 5.3 and 5.4 amount for 4.61% of all installs, which in my opinion means we could easily drop them. 5.5 only accounts for 10% of installs, but I'm in favor of keeping it as an "old-stable" kind of thing.

**Comment by javian** [comment]
I think my numbers might be off now that I give it a second thought. For instance with the last apache/sierra updates the people who issued the new command line option should be subtracted from the standard installs since they did not use the the option previously for instance. It doesn't change the numbers substantially though.

If we decide to boneyard the older formulas we'd still have a few problems to solve like how to deal with dependencies since the php formulas in most cases are not regular Formulas with self contained code in them.

**Comment by javian** [comment]
Also just to give it some additional context compared to other brew packages PHP 5.3 with ~1300 installs/updates in the last month puts it on the top 600 formulas of the ~8800 formula installs that were recorded in the last month.

**Comment by pdmulvey** [comment]
Hi all. I'll start by saying that I am very appreciative of the work done by the maintainers of this project, and I completely understand the impulse to drop the older, unsupported versions of PHP. Unfortunately, however, the real world does not march in time with PHP's release cycle, and so I'm here to argue the same point I made in #1327: these versions should be kept given how useful they are to developers stuck maintaining legacy code. 

There are still countless sites and applications out there running on PHP 5.3, 5.4, and 5.5. There are many developers who have to support such applications, as evidenced by the thousands of monthly downloads of the older PHP packages. I'm sure maintaining all these extra versions is a pain. But having them available is essential to developers such as myself whose daily workflows are kept manageable by brew-php. The ability to easily install and switch between different versions of PHP is an invaluable feature. 

If continuing to maintain and support these packages is unfeasible, I would say that the idea of "boneyarding" them so that they are still installable is a good compromise that will at least minimise the disruption to your end users. 

Thank you.

**Comment by medz** [comment]
作为一名中国开发中告诉你，尤其是mac下的phper，使用brew的意义在于，可以安装多个版本的php，并且使用brew link来快速切换，楼主，你不需要，不代表别人需要，就像楼上说的，很多厂商都支持这种情况，你不喜欢这样，那是你，不代表别人，日本可以为一个学生多保留几年一趟列车，为何Homebrew不可以为了虽然不多的老版本开发中需求而保留？哪怕只有一个人需要，为何不保留下来？推动技术革新是对的，但是你这种属于自私行为。我很不解，崇尚个人精神的你们，为什么会有你这种想法存在，我表示很惊讶。
其次，我故意使用我国家的语言来回复你，就是想让你知道，当你的想法实现了，会影响所在某国家的phper。希望你能调研下中国的数据。
Thinks.

**Comment by alcaeus** [comment]
As has been previously stated, there is a tap called "boneyard" which houses formula that are no longer supported. The idea is to move php53* and php54* there, so you could just do this:
```
brew tap homebrew/homebrew-boneyeard
brew install php53
```

Now, it may be that Google Translate didn't do a good job of the rest of your message, but rest assured, I suggested this not because I'm being selfish (ok, maybe I will appreciate updating two fewer formulae in the future) but because PHP 5.3 and PHP 5.4 have been end-of-lifed a while ago and are security risks at this time. If you are stuck supporting an old piece of software this may sound cynical, but it's time to move on.

**Comment by medz** [comment]
@alafon 
Thank you for your reply,
When I really hope to do so, is the official version of zend long-term support for PHP after the end of maintenance rather than now.
Thanks.

**Comment by josegonzalez** [comment]
@medz This is going to sound extra-harsh, but if thats the case, I'm sure Zend would be willing to provide official installation methods for now EOL'd versions of PHP. Given we aren't Zend, we're going to more closely follow the official deprecation cycle.

**Comment by Blackskyliner** [comment]
homebrew-boneyard was deprecated, so I guess the (old) packages will stay in this repository or what is the plan now?

https://github.com/Homebrew/homebrew-boneyard/commit/98b68c6b34a8d55caffd418c4940b397a60178ce

**Comment by alcaeus** [comment]
From what I read in homebrew/homebrew-boneyard#314, `brew install` will find deleted formulae, so we could safely remove them here.

**Comment by Blackskyliner** [comment]
Okay, but everyone who wants to use the old formulae/versions must then maintain their own tap otherwise it can't be installed, just to give an example of the first submention in your provided reference where 'libiomp' was discussed about not installable anymore (because there is no maintained tap available and boneyard was deprecated):

```
$> brew install libiomp
Error: No available formula with the name "libiomp"
==> Searching for a previously deleted formula...
libiomp was deleted from homebrew/core in commit 6dc67ddbb:
  libiomp: migrate to boneyard
  Functionality is now available as part of LLVM in Homebrew.

To show the formula before removal run:
  git -C "$(brew --repo homebrew/core)" show 6dc67ddbb^:Formula/libiomp.rb

If you still use this formula consider creating your own tap:
  http://docs.brew.sh/How-to-Create-and-Maintain-a-Tap.htm
```

A load of git tap repos could be created because of the need to use the old PHP versions because of legacy software and not everyone would register itself with the big brew registry to be found... I could be wrong on this and it's only my narrowed view on the topic but I just wanted to mention it ;-) 

-- Would have been somewhat better if they would have added an switch to just use this old checkout version of a package, but then I guess it would just be incompatible in some newer brew versions in the future and wouldn't install anyway so they didn't.

**Comment by alcaeus** [comment]
We're not talking about PHP 5.6 which has security support only. We're talking about 5.3 and 5.4, which have been EOL for almost 3 years and 2 years, respectively. If it gets harder for people to install these legacy versions, I'm ok with it. One of the reasons this was delayed was to possibly create a php boneyard to avoid polluting the boneyard tap with lots of php extensions. It's up to @javian and @josegonzalez to decide whether there should still be a boneyard tap or not.

**Comment by MikeMcQuaid** [comment]
As [announced on the 19th of January](https://brew.sh/2018/01/19/homebrew-1.5.0/) this tap will be archived by 31st March 2018. Various PHP formulae have been [migrated to Homebrew/homebrew-core](https://github.com/Homebrew/homebrew-php/blob/master/tap_migrations.json).
