### ISSUE TITLE
PHP Warning:  Module 'pdo_pgsql' already loaded in Unknown on line 0

### ISSUE THREAD

**Issue by kevinburke** [Homebrew/homebrew-php#3784]
## Description

I'm trying to use PHP with Postgres. After installing php70-pdo-pgsql, I get the following warning: `PHP Warning:  Module 'pdo_pgsql' already loaded in Unknown on line 0` when I run `php -v`.

I ran `brew install php70 --with-postgres`. Unfortunately I don't have the error now, but I got an error that suggested I needed to install additional pg drivers. So I tried installing php70-pdo-pgsql. After I installed the second package, I got the "Warning" in the title.

Commenting out the contents of ext-pdo_pgsql.ini seems to make everything work okay.

I've also checked my php.ini, there's nothing in there to suggest I'm loading it already. My php.ini and phpinfo are here: https://gist.github.com/kevinburke/c000f7fabd51ae58af0cf38644124992

## Context and Logs

Parameter | Value
--------- | ------------------
**OS X Version:**       | 10.11.6
**Homebrew Version:**   | 1.1.1
**PHP Version in use:** | 7.0.13
**Xcode Version:**      | not sure

**Output of gcc -v:**
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Output of php -v:**
PHP 7.0.13 (cli) (built: Nov 22 2016 21:39:28) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies

**Comment by javian** [comment]
Looking at it now it might be an oversight when seperating the postgres code into a seperate Formula. I believe that the option for php should have been removed when that happend.

**Comment by javian** [comment]
@kevinburke any update on this ?

**Comment by kevinburke** [comment]
Sorry I'm not sure what I'm supposed to do?

**Comment by javian** [comment]
I asked if you were intending to use the postgres PDO or native interface. =)

**Comment by javian** [comment]
@kevinburke I'm not sure how familiar you are with php and compiling the postgres support. In short there are 2 ways of connecting via php to postgres. The error that you describe in your issue looks like the same module is being loaded twice. This can happen if you install `--with-postgres`and at the same time install `php70-pdo-pgsql` because both options install the pdo module.

This is what I tried to describe in less words above and what you described in your issue but didn't quite understand. If you are OK with using the PDO module I would try and not install php with `--with-postgres` and only install the `php70-pgo-pgsql` formula instead and see if that works for you.

**Comment by bocharsky-bw** [comment]
I suppose this related to the #3896
