### ISSUE TITLE
php71 does not work with httpd

### ISSUE THREAD

**Issue by tfe2012** [Homebrew/homebrew-php#3960]
## Description

run brew reinstall php71 --with-httpd

And now I get apache error: Cannot load /usr/local/Cellar/php71/7.1.1_12/libexec/apache2/libphp7.so

This folder does not exist /usr/local/Cellar/php71/7.1.1_12/libexec/

## Context and Logs

Parameter | Value
--------- | ------------------
**OS X Version:**       | last
**Homebrew Version:**   | brew -v Homebrew 1.1.9
**PHP Version in use:** | 7.1.1_12
**Xcode Version:**      | last

**Output of gcc -v:**

**Output of php -v:**

**Build logs:** _Link to public gist created with `brew gist-logs my-formula`_

**Comment by hainuo** [comment]
需要执行 ```xcode-select --install```

**Comment by angelxaces** [comment]
## Here's how I fixed mine

Hey guys, I have to admit this totally had me too. The `xcode-select --install` didn't work for me. The thing is that I just had it running but me being me, I saw the update from 7.1.4 to 7.1.5 not too long ago and of course I "needed" it. I absentmindedly went the uninstall route rather than the upgrade route and couldn't remember how I got past this the first time. because writing it down would be too logical. So I'm doing it now and hopefully it helps someone here.

__Build it from the source__ (bottom, bare-bones solution here):
`brew install php71 --with-httpd24 --build-from-source`

__My loadout__ (I had some conflicts with the database support):
 `brew install php71 --with-enchant --with-gmp --with-webp --with-httpd24 --with-cgi --with-debug --with-homebrew-curl --with-homebrew-libressl --with-homebrew-libxslt --with-homebrew-libxml2 --with-imap --with-pear --with-phpdbg --with-thread-safety --build-from-source`

Those are the two that got me through this without losing whatever sanity I have left. I could do
`brew install php71` no problem and I could do the above but it would fail out if it was just 
`brew install php71 --with-httpd24`

Trouble is that by doing it this way, specifying `--with-*` you've made brew think that if you want something you'll ask for it, at least that's my understanding given my end result. You don't get the SSL support, the database support, no passing go or collecting $200 unless `--with-\$200` is specified.

For easy copy/past:
```bash
--with-cgi --with-debug --with-enchant --with-gmp --with-homebrew-curl \
--with-homebrew-libressl --with-homebrew-libxml2 --with-homebrew-libxslt \
--with-httpd24 --with-imap --with-libmysql --with-mssql --with-pdo-oci \
--with-pear --with-phpdbg --with-postgresql --with-thread-safety \
--with-webp --without-bz2 --without-fpm --without-ldap \
--without-legacy-mysql --without-mysql --without-pcntl --without-unixodbc \
--HEAD --build-from-source
```
Because this issue is with passing `--with-httpd24` I kept that in but you can also do `--with-httpd22` as well. I also ran into a snag with any SQL/Oracle support but that's another issue entirely. Rule of thumb: Just take what you know you'll need.

PHP 7.1 options:
```bash
* --with-cgi
	Enable building of the CGI executable (implies * --without-fpm)
* --with-debug
	Compile with debugging symbols
* --with-enchant
	Build with enchant support
* --with-gmp
	Build with gmp support
* --with-homebrew-curl
	Include Curl support via Homebrew
* --with-homebrew-libressl
	Include LibreSSL instead of OpenSSL via Homebrew
* --with-homebrew-libxml2
	Include Libxml2 support via Homebrew
* --with-homebrew-libxslt
	Include LibXSLT support via Homebrew
* --with-httpd22
	Enable building of shared Apache 2.2 Handler module
* --with-httpd24
	Enable building of shared Apache 2.4 Handler module
* --with-imap
	Include IMAP extension
* --with-libmysql
	Include (old-style) libmysql support instead of mysqlnd
* --with-mssql
	Include MSSQL-DB support
* --with-pdo-oci
	Include Oracle databases (requries ORACLE_HOME be set)
* --with-pear
	Build with PEAR
* --with-phpdbg
	Enable building of the phpdbg SAPI executable
* --with-postgresql
	Build with postgresql support
* --with-thread-safety
	Build with thread safety
* --with-webp
	Build with webp support
* --without-bz2
	Build without bz2 support
* --without-fpm
	Disable building of the fpm SAPI executable
* --without-ldap
	Build without LDAP support
* --without-legacy-mysql
	Do not include the deprecated mysql_ functions
* --without-mysql
	Remove MySQL/MariaDB support
* --without-pcntl
	Build without Process Control support
* --without-unixodbc
	Build without unixODBC support
* --HEAD
	Install HEAD version
```
If you need to see what is going on add `-vd` for verbose debugging mode.

For more information about installation options you can use:
`brew install --help`

**Comment by SMillerDev** [comment]
Seeing how there's no more replies after the detailed explanation (thanks for that) I assume this is now fixed?

**Comment by angelxaces** [comment]
lol idk. perhaps it helped. No one has messaged me personally so I would guess so.
