### ISSUE TITLE
upgraded and all my setup got broken

### ISSUE THREAD

**Issue by neohunter** [Homebrew/homebrew-php#4216]
I'm running El Capitan.

Was using factory osx apache with brew php55. I installed php-imagick and everyhting stop working.

`sudo apachectl -T` says:

```
httpd: Syntax error on line 173 of /private/etc/apache2/httpd.conf: Cannot load /usr/local/opt/php55/libexec/apache2/libphp5.so into server: dlopen(/usr/local/opt/php55/libexec/apache2/libphp5.so, 10): image not found
```

Checking, the file does not exist.

Reading the `brew info php55` says that it not longer comes with the .so extensions if i try to install with http24 it intall this formula `homebrew/apache/httpd24` which im not interested.

How I can use only php from brew and keep using my osx apache?

**Comment by javian** [comment]
You should be able to link to the same .so that's created as far as I know. The httpd24 Formula is required to make it compile since Apple has removed the supporting scripts that makes it possible. There are "hacks" you can do to your computer which are documented in other issues to make it compile but that's not something we support.
