### ISSUE TITLE
opcache.enable_cli is enabled by default as of PHP 7.1.2 (but later reverted)

### ISSUE THREAD

**Issue by pinepain** [Homebrew/homebrew-php#4297]
**UPD (Sept 10, 2017):** later `opcache.enable_cli` was reverted to `0`.

Old text: 
`opcache.enable_cli` is enabled by default as of PHP 7.1.2 (http://php.net/manual/en/opcache.configuration.php), though both [php71-opcache.rb](https://github.com/Homebrew/homebrew-php/blob/master/Formula/php71-opcache.rb#L49) and [php72-opcache.rb](https://github.com/Homebrew/homebrew-php/blob/master/Formula/php72-opcache.rb#L49) have it disabled by default (I guess for historical reasons).

Shall this be changes to be consistent with other platforms defaults?

**Comment by javian** [comment]
Sounds like a good idea to me. I don't know the history of it being disabled by default but looking at the url in the Formula referencing the defaults that source has not been updated for the past 2 years. The opcache formula is decently popular so any change would have a definite impact assuming the change is noticeable. Have you tested it ?

I'm also not sure why the file is there since most if not all the settings are set to the default value so it doesn't really serve any purpose except for documenting the parameters.

**Comment by pinepain** [comment]
Hi, sorry for late reply. It came up that `opcache.enable_cli` setting [has been reverted](https://github.com/php/php-src/commit/e9ff1fac85b97c677e33210770f87f7dc4bc5a24). However, it doesn't seem to be useful to provide ini for opcache extension. Comparing `php -i | grep opcache` with custom ini and using defaults shows no functional difference.

**Comment by javian** [comment]
Merged
