### ISSUE TITLE
php7x-swoole: beta packages used as "stable"

### ISSUE THREAD

**Issue by hdogan** [Homebrew/homebrew-php#4377]
According to https://pecl.php.net/package/swoole version 2 is not stable yet. I think using latest stable version (1.9.X) is better.

**Comment by alcaeus** [comment]
I'm a bit confused - the earliest 2.0.x version I could find on https://pecl.php.net/package/swoole is 2.0.4. Released in December 2016 and marked as beta. Since then there have been 4 more releases, also marked as beta. Maybe it would be worth asking the maintainers whether the formula is actually beta.

I don't think downgrading to 1.9 at this time is a good idea, since people might already be relying on 2.0.x being installed.

**Comment by hdogan** [comment]
I'm following swoole repository actively on github. 1.9 is most active branch at the moment (general bug fixes and covertiy scan fixes), but I have no idea how the author tag and manage releases. They sometime just push the release without testing, etc.

**Comment by javian** [comment]
I noticed that even on Github it says 2.0.x "pre-release". If I do `pecl install swoole` I'm assuming it will install version 1.9 ?

**Comment by hdogan** [comment]
It currently installs 1.9.18 (stable) release.

**Comment by SMillerDev** [comment]
Maybe we should make a new formula set swoole@1?

**Comment by hdogan** [comment]
Since 2.0.10 is tagged as stable by author this issue is not valid anymore.

https://github.com/swoole/swoole-src/releases/tag/v2.0.10-stable
