### ISSUE TITLE
I am not able to set the imagick module in php

### ISSUE THREAD

**Issue by parkwookyun** [Homebrew/homebrew-php#4420]
## Description

I have a problem installing imagick and loading modules from php, but I have not found the cause of any problems at all. What is the workaround for this problem?

**For additional reference, my version**

- imagemagick -v7.0.6-9
- php56-imagick -v3.4.3_4

**Installation proccess**
`brew install imagemagick`
`brew install php56-imagick --build-from-source`

**My php.ini**
`extension="/usr/local/Cellar/php56-imagick/3.4.3_4/imagick.so'"`

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       | v10.12.5
**Homebrew version:**   | v1.3.1
**PHP version in use:** | v5.6.31
**Xcode version:**      | _your Xcode version (output of `xcodebuild -version`)_

**Output of `gcc -v`:**
_result of the CLI output_

**Output of `php -v`:**
[25-Aug-2017 12:40:55 Europe/Berlin] PHP Warning: PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php56-imagick/3.4.3_4/imagick.so' - dlopen(/usr/local/Cellar/php56-imagick/3.4.3_4/imagick.so, 9): Library not loaded: /usr/local/opt/freetype/lib/libfreetype.6.dylib

Referenced from: /usr/local/opt/imagemagick/lib/libMagickWand-7.Q16HDRI.3.dylib

Reason: Incompatible library version: libMagickWand-7.Q16HDRI.3.dylib requires version 21.0.0 or later, but libfreetype.6.dylib provides version 15.0.0 in Unknown on line 0

**Build logs:** _Link to public gist created with `brew gist-logs my-formula`_

**Comment by SMillerDev** [comment]
The imagemagick formula does recommend installing freetype, there's 2 short term solutions here.

1. install freetype (`brew install freetype`)
2. try installing imagemagick using `--without-freetype`

**Comment by monking** [comment]
I had the [nearly*] same issue on macOS Sierra, and `freetype` was already installed, as @SMillerDev anticipated. Doing `brew reinstall php56-imagick --without-freetype` got me up and running again.

\* I didn't run `php -v`, and saw no reference to `freetype`, but had the same warning re: `libMagickWand-7.Q16HDRI.3.dylib` in Apache error logs.

**Comment by SMillerDev** [comment]
Could it be that you're using the build in PHP?

**Comment by AngeloLazzari** [comment]
hi everyone, i have the same problem

[15-Sep-2017 12:31:20 Europe/Berlin] PHP Warning:  PHP Startup: Unable to load dynamic library '/Applications/XAMPP/xamppfiles/lib/php/extensions/no-debug-non-zts-20131226/imagick.so' - dlopen(/Applications/XAMPP/xamppfiles/lib/php/extensions/no-debug-non-zts-20131226/imagick.so, 9): Library not loaded: /usr/local/opt/freetype/lib/libfreetype.6.dylib
  Referenced from: /usr/local/opt/imagemagick/lib/libMagickWand-7.Q16HDRI.4.dylib
  Reason: Incompatible library version: libMagickWand-7.Q16HDRI.4.dylib requires version 21.0.0 or later, but libfreetype.6.dylib provides version 15.0.0 in Unknown on line 0

i have different version of the lib

MacBook-Pro:no-debug-non-zts-20131226 angelolazzari$ locate libfreetype.6.dylib
/Applications/MAMP/Library/lib/libfreetype.6.dylib
/Applications/XAMPP/xamppfiles/lib/libfreetype.6.dylib
/usr/X11/lib/libfreetype.6.dylib
/usr/local/Cellar/freetype/2.8/lib/libfreetype.6.dylib
/usr/local/lib/libfreetype.6.dylib
/usr/local/php5-5.6.31-20170817-164511/lib/libfreetype.6.dylib

and if a do:
MacBook-Pro:no-debug-non-zts-20131226 angelolazzari$ brew link --overwrite freetype
Warning: Already linked: /usr/local/Cellar/freetype/2.8
To relink: brew unlink freetype && brew link freetype

i think i have the last version available...
this problem is driving me crazy... can you help me please?

**Comment by SMillerDev** [comment]
what happens when you run `brew reinstall -s imagemagick` and  `brew reinstall -s php56-imagick` @AngeloLazzari ?

**Comment by AngeloLazzari** [comment]
hi, thank you for the response. 

Now things seem to move a bit to the solution... but... when i launch apache....the log tells me:

dyld: Symbol not found: _png_get_header_ver
  Referenced from: /usr/local/Cellar/imagemagick/7.0.7-1/lib/ImageMagick/modules-Q16HDRI/coders/png.so
  Expected in: /Applications/XAMPP/xamppfiles/lib/libfreetype.6.dylib

no idea whats happen now... :/

THank you

**Comment by JohnConstantin** [comment]
![imageedit__8014361642](https://user-images.githubusercontent.com/14069427/30803960-ef1c154a-a1eb-11e7-8c60-220635894f89.jpg)
run brew reinstall -s imagemagick and brew reinstall -s php56-imagick @SMillerDev 
then remove /usr/local/etc/php/5.6/conf.d/ext-imagick.ini

**Comment by SMillerDev** [comment]
I didn't have this issue. @AngeloLazzari it seems mixing XAMPP with homebrew installed php components doesn't work as well, as it ships its own.
I'd recommend using either XAMPP or homebrew php.

As for @parkwookyun can I take from this silence that the issue is resolved?
