### ISSUE TITLE
homebrew/php/php71: this formula has no --with-httpd option so it will be ignored!

### ISSUE THREAD

**Issue by freedmandil** [Homebrew/homebrew-php#4494]
## Description

homebrew/php/php71: this formula has no --with-httpd option so it will be ignored!

upgrade php71 and suddenly no libexec to add in httpd module list
it is utterly nonsensical to upgrade httpd and deprecate names without testing to see if the scripts work!!!!!!!!!!!

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       | 10.12
**Homebrew version:**   | 1.3.4
**PHP version in use:** | 7.1.8
**Xcode version:**      | 8.0

**Output of `gcc -v`: 9.0
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.37)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Output of `php -v`:**
PHP 5.6.30 (cli) (built: Feb  7 2017 16:18:37)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies

**Build logs:** _Link to public gist created with `brew gist-logs my-formula`_

**Comment by SMillerDev** [comment]
That option hasn't existed anymore since at least 6 months. You have to specify a version now `--with-httpd` or `--with-httpd24`.

**Comment by ChrisWatterston** [comment]
I didn't realise things were migrating, ran `brew update` and `brew upgrade` right in the middle of development (school boy error) and it killed my PHP56 running within the built-in MacOS Apache - ouch!! I spent around 4 hours trying to get things running again with no success, has that `libexec` folder gone on holiday?

In the end, I stopped the built-in Apache used `brew install httpd24` to see if that made a difference but now when trying to install `brew install php56 --with-httpd24` I get `Warning: Use httpd instead of deprecated homebrew/apache/httpd24`.... and then when I go for `brew reinstall php56 --with-httpd` I get `Warning: homebrew/php/php56: this formula has no --with-httpd option so it will be ignored!`..... errrrrr *scratches head*

Not exactly to sure what's going on here?

**Comment by SMillerDev** [comment]
@ChrisWatterston This issue is about php71. As for the build in apache, Apple doesn't ship tools to make that work anymore since Sierra so homebrew can't build compatibility for that anymore.
There's multiple issues about this still open. Some people are reporting successfully using the binary for homebrew apache with the build in apache but you'll have to check in the other issues.

**Comment by ChrisWatterston** [comment]
@SMillerDev Thanks. I tried PHP71 but also got `Warning: homebrew/php/php71: this formula has no --with-httpd option so it will be ignored!` with `brew reinstall php71 --with-httpd`. Did try with 

I'll take a look at using the binary and see how things turn out.

**Comment by alexfinnarn** [comment]
I just tried 

```
brew reinstall php72 --with-httpd
==> Reinstalling homebrew/php/php72 
Warning: homebrew/php/php72: this formula has no --with-httpd option so it will be ignored!
```

So, I can confirm what @ChrisWatterston sees. I'd be interested if "using the binary" worked.

**Comment by freedmandil** [comment]
installing from scratch removing all symlinks and config files and
installing httpd and then adding --with-httpd24 in the php71 brew
installation
the errors about httpd24 deprecated to httpd are manifold and the libexec
folder is nonetheless created.

Daniel



-
Rabbi Daniel Freedman
Administration / Graphics
Ohr Somayach International, Jerusalem, Israel
daniel@ohr.edu Mobile: 058-331-9984 (Intl: +972 58 331 9 984)

This communication is intended for the addressee(s) only. It is
confidential. If you have received this communication in error, please
notify us immediately and destroy the original message. You may not copy or
disseminate this communication without the permission of the sendee(s).
Only authorized signatories are competent to enter into agreements on
behalf of Ohr Somayach International.  Recipient(s) are thus advised that
the content of this message may not be legally binding on Ohr Somayach
International and may contain the personal views and opinions of the
author, which are not necessarily the views and opinions of Ohr Somayach
International. All agreements between Ohr Somayach and outsiders are
subject to Israeli and/or (where applicable) US Law unless Ohr Somayach
agrees in writing to the contrary.

**Comment by ChrisWatterston** [comment]
@alexfinnarn I can confirm what @freedmandil highlights is correct - but strangely it didn't work yesterday evening when I tried... very odd - But thanks 👍 

Anyhow, I now have the `libexec` folder and can successfully load a `phpinfo()` page.

When running `brew reinstall php71 --with-httpd` I still getting a ton of `Warning: Use httpd instead of deprecated homebrew/apache/httpd24`, then a `==> Reinstalling homebrew/php/php71 --with-httpd24`, and finally a `Warning: homebrew/php/php71: this formula has no --with-httpd option so it will be ignored!` warning, **or is this just a bug?**

**Comment by javian** [comment]
This should now have been corrected through #4500 .

**Comment by ChrisWatterston** [comment]
Thanks @javian, I need to rebuild my other desktop Mac to High Sierra (did my MacBook couple days ago) so fingers crossed it will go smoothly when it comes to having a "Brew" 👍  cheers!

**Comment by alexfinnarn** [comment]
I tried `brew reinstall php72 --with-httpd` and did not get "this formula has no --with-httpd option so it will be ignored". So, it seems like the extra steps mentioned above are not needed anymore. 

If you get another confirmation, then I think this issue can be considered resolved.
