### ISSUE TITLE
Installing php55 and php56 makes my mac terminal dead

### ISSUE THREAD

**Issue by ohpyupi** [Homebrew/homebrew-php#4602]
## Description

Hi, I came up with some httpd issue. I have been doing everything that I can try.
So I tried to reinstall php56 on my mac machine, but at the "make" step, the fan goes crazy, and suddenly the terminal goes freeze. I tried php55, and it doesn't work as well.

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       | High Sierra 10.13.1
**Homebrew version:**   | 1.3.x
**PHP version in use:** | 5.6
**Xcode version:**   | 

**Output of `gcc -v`:**
_result of the CLI output_

**Output of `php -v`:**
_result of the CLI output_

**Build logs:** _Link to public gist created with `brew gist-logs my-formula`_

**Comment by javian** [comment]
It takes a while for make to complete - how long did you wait ?

**Comment by guicastro** [comment]
brew install php56 --with-httpd
Updating Homebrew...
==> Installing php56 from homebrew/php
==> Downloading https://php.net/get/php-5.6.32.tar.bz2/from/this/mirror
Already downloaded: /Users/guilherme/Library/Caches/Homebrew/php56-5.6.32
==> ./configure --prefix=/usr/local/Cellar/php56/5.6.32_8 --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc/php/5.6 -
Last 15 lines from /Users/guilherme/Library/Logs/Homebrew/php56/01.configure:
checking whether to use system default cipher list instead of hardcoded value... no
checking for krb5-config... /usr/bin/krb5-config
checking for DSA_get_default_method in -lssl... no
checking for X509_free in -lcrypto... yes
checking for RAND_egd... no
checking for pkg-config... no
checking for OpenSSL version... >= 0.9.6
checking for CRYPTO_free in -lcrypto... yes
checking for SSL_CTX_set_ssl_version in -lssl... yes
checking for PCRE library to use... bundled
checking whether to enable the SQLite3 extension... yes
checking bundled sqlite3 library... yes
checking for ZLIB support... yes
checking if the location of ZLIB install directory is defined... no
configure: error: Cannot find libz

READ THIS: https://docs.brew.sh/Troubleshooting.html

These open issues may also help:
Installing php55 and php56 makes my mac terminal dead https://github.com/Homebrew/homebrew-php/issues/4602
php56-mongodb _clock_gettime error at runtime https://github.com/Homebrew/homebrew-php/issues/3737

**Comment by SMillerDev** [comment]
@gabrielizaias wouldn't really classify that as dead, that's a simple case of missing command line tools.

**Comment by gabrielizaias** [comment]
@SMillerDev I think you tagged the wrong user mate

**Comment by SMillerDev** [comment]
Yeah, not sure where that came from. I meant @guicastro

**Comment by javian** [comment]
@guicastro That error indicates that you need to run `xcode-select --install` to reinstall the libz headers.
